import CustomImage from './CustomImage';
import AnimalTable from './AnimalTable';
import CarouselImages from './CarouselImages';
export { default as CustomButton } from './CustomButton';
export { default as CustomInput } from './CustomInput';
export { default as FromDevora } from './FromDevora';
export { default as LogoContainer } from './LogoContainer';
export { default as Header } from './Header';
export { default as CustomImage } from './CustomImage';
export { default as AnimalCard } from './AnimalCard';
export {default as AnimalTable} from './AnimalTable';
export { default as DataViewAnimal } from './DataViewAnimal';
export { default as ModalButton } from './ModalButton';
export { default as RowRegister } from './RowRegister';
export { default as HeaderRegisterTable } from './HeaderRegisterTable';
export { default as CustomSelect } from './CustomSelect';
export { default as CustomDatePicker } from './CustomDatePicker';
export {default as CarouselImages} from './CarouselImages';